name: Tests And Linting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pre-Commit
        run: python -m pip install pre-commit && pre-commit install

      - name: Load cached Pre-Commit Dependencies
        id: cached-pre-commit-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Execute Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: pdm-project/setup-pdm@v3
        name: Set up PDM
        with:
          python-version: "3.11"
          allow-python-prereleases: true
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm install -G:all

      - name: Type Check
        run: pdm run mypy .

  test:
    name: "Test (Python ${{ matrix.python-version }}, Litestar ${{ matrix.litestar-version || 'latest' }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        include:
          - python-version: "3.12"
            litestar-version: "2.0"
          - python-version: "3.12"
            litestar-version: "2.1"
          - python-version: "3.12"
            litestar-version: "2.2"
          - python-version: "3.12"
            litestar-version: "2.3"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }}
        id: checkout-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create cache file
        run: echo '${{ matrix.python-version }}-${{ matrix.litestar-version }}' > ./matrix-cache-file.txt

      - uses: pdm-project/setup-pdm@v3
        name: Set up PDM
        with:
          python-version: ${{ matrix.python-version }}
          allow-python-prereleases: true
          cache: true
          cache-dependency-path: |
            ./pdm.lock
            ./matrix-file.txt

      - name: Install Litestar
        if: ${{ matrix.litestar-version }}
        run: pdm add --no-sync 'litestar==${{ matrix.litestar-version }}'

      - name: Install dependencies
        run: pdm sync -G:all

      - name: Run the tests
        run: pdm run pytest tests
