name: Publish to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    - name: Check out repository
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - uses: pdm-project/setup-pdm@v3
      name: Set up PDM
      with:
        python-version: "3.12"
        cache: true

    - name: Build package
      run: pdm build

    - name: upload release to PyPI
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
